#!/usr/bin/env bash

set -eux

# the directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# the temp directory used, within $DIR
# omit the -p parameter to create a temporal directory in the default location
WORK_DIR=`mktemp -d -p "$DIR"`

# check if tmp dir was created
if [[ ! "$WORK_DIR" || ! -d "$WORK_DIR" ]]; then
  echo "Could not create temp dir"
  exit 1
fi

# deletes the temp directory
function cleanup {
  rm -rf "$WORK_DIR"
  echo "Deleted temp working directory $WORK_DIR"
}

# register the cleanup function to be called on the EXIT signal
trap cleanup EXIT

########

cd $WORK_DIR

## remove files
if [[ -f /var/mobile/opt/bin/chflags.page.liam ]]; then
  rm /var/mobile/opt/bin/chflags.page.liam
fi
if [[ -f /var/mobile/opt/bin/chown.page.liam ]]; then
  rm /var/mobile/opt/bin/chown.page.liam
fi
if [[ -f /var/mobile/opt/bin/launchctl.page.liam ]]; then
  rm /var/mobile/opt/bin/launchctl.page.liam
fi
